# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# Specifies the JVM arguments used for the daemon process.
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Enable Gradle build cache
org.gradle.caching=true

# Keep Gradle daemon running
org.gradle.daemon=true

# Do not build projects in parallel
org.gradle.parallel=false

# Enable configuration cache
org.gradle.configuration-cache=true